#!/usr/bin/env python3
"""
Walk-forward tuning for combined stock-ranking weights.

This script does not rebuild SEC fair-value scores. It consumes the
point-in-time score history generated by combined_score_backtest.py, then
re-ranks each historical anchor under different trend/fair-value/regime weight
matrices.

Workflow:
1. Load point-in-time score snapshots.
2. Load historical prices once for forward-return/risk evaluation.
3. Test candidate weight matrices.
4. Select weights on older folds and validate on the next fold.
5. Save return, drawdown, volatility, Sharpe/Sortino, capture, and tracking
   metrics for audit.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

import comp
import historical_data_layer as historical_data
import portfolio_backtest_metrics as portfolio_metrics
import regime_threshold_backtest as regime_bt


DEFAULT_SCORE_HISTORY = Path("backtests/combined_score/point_in_time_scores.csv")
DEFAULT_OUTPUT_DIR = Path("backtests/weight_tuning")
HORIZONS = regime_bt.HORIZONS
BENCHMARK_TICKERS = regime_bt.BENCHMARK_TICKERS
FOLD_ORDER = ["5-4", "4-3", "3-2", "2-1", "1-current"]


@dataclass(frozen=True)
class WeightConfig:
    config_id: str
    notes: str
    trend_w_bull_bull: float
    trend_w_bull_early: float
    trend_w_bull_neutral: float
    trend_w_neutral_bull: float
    trend_w_neutral_early: float
    trend_w_neutral_neutral: float
    trend_w_bull_bear: float
    trend_w_bear_any: float
    fair_value_missing_fill: float | None = None

    def trend_weight(self, industry_regime: str | None, subindustry_regime: str | None) -> float:
        industry = industry_regime if isinstance(industry_regime, str) else "Neutral"
        subindustry = subindustry_regime if isinstance(subindustry_regime, str) else "Neutral"
        industry = industry.strip()
        subindustry = subindustry.strip()
        if industry == "EarlyBull":
            industry = "Bull"

        if industry == "Bull" and subindustry == "Bull":
            return self.trend_w_bull_bull
        if industry == "Bull" and subindustry == "EarlyBull":
            return self.trend_w_bull_early
        if industry == "Bull" and subindustry == "Neutral":
            return self.trend_w_bull_neutral
        if industry == "Neutral" and subindustry == "Bull":
            return self.trend_w_neutral_bull
        if industry == "Neutral" and subindustry == "EarlyBull":
            return self.trend_w_neutral_early
        if industry == "Neutral" and subindustry == "Neutral":
            return self.trend_w_neutral_neutral
        if industry == "Bull" and subindustry == "Bear":
            return self.trend_w_bull_bear
        return self.trend_w_bear_any


def current_live_config() -> WeightConfig:
    return WeightConfig(
        config_id="current_live",
        notes="Current production trend/fair-value regime weight matrix",
        trend_w_bull_bull=0.60,
        trend_w_bull_early=0.55,
        trend_w_bull_neutral=0.50,
        trend_w_neutral_bull=0.45,
        trend_w_neutral_early=0.45,
        trend_w_neutral_neutral=0.40,
        trend_w_bull_bear=0.40,
        trend_w_bear_any=0.30,
    )


def curated_configs() -> list[WeightConfig]:
    return [
        current_live_config(),
        WeightConfig(
            config_id="value_heavy_defensive",
            notes="Keeps fair value dominant except in clearly bullish regimes",
            trend_w_bull_bull=0.45,
            trend_w_bull_early=0.40,
            trend_w_bull_neutral=0.35,
            trend_w_neutral_bull=0.35,
            trend_w_neutral_early=0.30,
            trend_w_neutral_neutral=0.25,
            trend_w_bull_bear=0.25,
            trend_w_bear_any=0.15,
        ),
        WeightConfig(
            config_id="balanced_low_regime_spread",
            notes="Moderate trend/fair-value blend with smaller regime jumps",
            trend_w_bull_bull=0.55,
            trend_w_bull_early=0.50,
            trend_w_bull_neutral=0.45,
            trend_w_neutral_bull=0.45,
            trend_w_neutral_early=0.40,
            trend_w_neutral_neutral=0.35,
            trend_w_bull_bear=0.35,
            trend_w_bear_any=0.25,
        ),
        WeightConfig(
            config_id="trend_heavy_bullish",
            notes="Lets momentum dominate when industry/subindustry regimes are bullish",
            trend_w_bull_bull=0.75,
            trend_w_bull_early=0.70,
            trend_w_bull_neutral=0.60,
            trend_w_neutral_bull=0.60,
            trend_w_neutral_early=0.55,
            trend_w_neutral_neutral=0.45,
            trend_w_bull_bear=0.35,
            trend_w_bear_any=0.20,
        ),
        WeightConfig(
            config_id="trend_heavy_all_weather",
            notes="Higher trend weight in most regimes, including neutral conditions",
            trend_w_bull_bull=0.75,
            trend_w_bull_early=0.70,
            trend_w_bull_neutral=0.65,
            trend_w_neutral_bull=0.65,
            trend_w_neutral_early=0.60,
            trend_w_neutral_neutral=0.55,
            trend_w_bull_bear=0.45,
            trend_w_bear_any=0.35,
        ),
        WeightConfig(
            config_id="bear_value_anchor",
            notes="Keeps bearish-regime picks mostly fundamental instead of momentum-driven",
            trend_w_bull_bull=0.60,
            trend_w_bull_early=0.55,
            trend_w_bull_neutral=0.45,
            trend_w_neutral_bull=0.40,
            trend_w_neutral_early=0.35,
            trend_w_neutral_neutral=0.30,
            trend_w_bull_bear=0.25,
            trend_w_bear_any=0.15,
        ),
        WeightConfig(
            config_id="neutral_fair_value_50_fill",
            notes="Exploratory trend fallback: missing fair-value scores are filled at neutral 50",
            trend_w_bull_bull=0.60,
            trend_w_bull_early=0.55,
            trend_w_bull_neutral=0.50,
            trend_w_neutral_bull=0.45,
            trend_w_neutral_early=0.45,
            trend_w_neutral_neutral=0.40,
            trend_w_bull_bear=0.40,
            trend_w_bear_any=0.30,
            fair_value_missing_fill=50.0,
        ),
    ]


def grid_config(base: float, bull_lift: float, bear: float) -> WeightConfig:
    def bounded(value: float, low: float = 0.05, high: float = 0.85) -> float:
        return round(float(min(max(value, low), high)), 3)

    return WeightConfig(
        config_id=(
            f"grid_base{int(base * 100)}_"
            f"bull{int(bull_lift * 100)}_bear{int(bear * 100)}"
        ),
        notes=(
            "Expanded grid candidate: base neutral trend weight plus bullish "
            "regime lift and bearish trend cap."
        ),
        trend_w_bull_bull=bounded(base + bull_lift + 0.05),
        trend_w_bull_early=bounded(base + bull_lift),
        trend_w_bull_neutral=bounded(base + bull_lift / 2.0),
        trend_w_neutral_bull=bounded(base + min(0.10, bull_lift / 2.0)),
        trend_w_neutral_early=bounded(base + 0.05),
        trend_w_neutral_neutral=bounded(base),
        trend_w_bull_bear=bounded(max(bear, base - 0.05), high=0.55),
        trend_w_bear_any=bounded(bear, high=0.45),
    )


def build_candidate_configs(preset: str) -> list[WeightConfig]:
    configs = curated_configs()
    if preset == "expanded":
        for base in (0.25, 0.35, 0.45, 0.55):
            for bull_lift in (0.05, 0.15, 0.25):
                for bear in (0.15, 0.25, 0.35):
                    configs.append(grid_config(base, bull_lift, bear))

    unique = {}
    for config in configs:
        unique.setdefault(config.config_id, config)
    return list(unique.values())


def prepare_score_history(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Point-in-time score history not found: {path}")

    scores = pd.read_csv(path)
    required = {
        "Date",
        "Ticker",
        "Fair_Value_Score",
        "Industry_Regime",
        "SubIndustry_Regime",
    }
    missing = sorted(required - set(scores.columns))
    if missing:
        raise RuntimeError(f"Score history is missing required columns: {missing}")

    scores["Date"] = pd.to_datetime(scores["Date"], errors="coerce").dt.normalize()
    scores["Ticker"] = scores["Ticker"].astype(str).str.upper()
    scores["Fair_Value_Score"] = pd.to_numeric(scores["Fair_Value_Score"], errors="coerce")

    if "Stock_Price_Trend_Score" in scores.columns:
        trend = pd.to_numeric(scores["Stock_Price_Trend_Score"], errors="coerce")
    elif "Price_Trend_Score" in scores.columns:
        trend = pd.to_numeric(scores["Price_Trend_Score"], errors="coerce")
        trend = trend.where(trend > 1.0, trend * 100.0)
    else:
        raise RuntimeError("Score history is missing a stock price-trend score column")

    scores["Trend_Score_100"] = trend
    scores = scores.dropna(subset=["Date", "Ticker", "Trend_Score_100"])
    scores = scores.sort_values(["Date", "Ticker"]).reset_index(drop=True)
    return scores


def fetch_price_wide(
    scores: pd.DataFrame,
    batch_size: int,
    historical_price_file: Path | None = None,
) -> pd.DataFrame:
    tickers = sorted(set(scores["Ticker"]) | set(BENCHMARK_TICKERS))
    start_date = scores["Date"].min() - pd.Timedelta(days=5)
    end_date = pd.Timestamp.today().normalize() + pd.Timedelta(days=1)

    if historical_price_file is not None:
        print(f"[INFO] Loading canonical price history from {historical_price_file}", flush=True)
        price_wide = historical_data.load_canonical_price_wide(
            path=historical_price_file,
            tickers=tickers,
            start_date=start_date,
            end_date=end_date,
            value_column="Close",
        )
        missing = sorted(set(tickers) - set(price_wide.columns))
        if missing:
            print(
                f"[WARN] Canonical price file is missing {len(missing)} requested tickers",
                flush=True,
            )
            print(f"Sample missing tickers: {missing[:20]}", flush=True)
        if price_wide.empty:
            raise RuntimeError("No canonical price data returned; cannot tune weights")
        return price_wide

    raw = comp.fetch_all_prices(
        tickers=tickers,
        start_date=start_date.strftime("%Y-%m-%d"),
        end_date=end_date.strftime("%Y-%m-%d"),
        batch_size=batch_size,
    )
    price_data = regime_bt.normalize_price_data(raw)
    missing = sorted(set(tickers) - set(price_data))
    if missing:
        print(f"[INFO] Retrying {len(missing)} missing price tickers individually", flush=True)
        retry_raw = comp.fetch_all_prices(
            tickers=missing,
            start_date=start_date.strftime("%Y-%m-%d"),
            end_date=end_date.strftime("%Y-%m-%d"),
            batch_size=1,
            max_retries=3,
            sleep_seconds=0.25,
        )
        price_data.update(regime_bt.normalize_price_data(retry_raw))

    price_wide = regime_bt.build_price_wide(price_data)
    if price_wide.empty:
        raise RuntimeError("No price data returned; cannot tune weights")
    return price_wide


def config_score_frame(scores: pd.DataFrame, config: WeightConfig) -> pd.DataFrame:
    df = scores.copy()
    fair_value = df["Fair_Value_Score"].copy()
    if config.fair_value_missing_fill is not None:
        fair_value = fair_value.fillna(float(config.fair_value_missing_fill))

    df["Tuned_Fair_Value_Score"] = fair_value
    df = df[np.isfinite(df["Trend_Score_100"]) & np.isfinite(df["Tuned_Fair_Value_Score"])].copy()
    if df.empty:
        return df

    df["Trend_Weight"] = [
        config.trend_weight(industry, subindustry)
        for industry, subindustry in zip(df["Industry_Regime"], df["SubIndustry_Regime"])
    ]
    df["Fair_Value_Weight"] = 1.0 - df["Trend_Weight"]
    df["Tuned_Combined_Score"] = (
        df["Trend_Weight"] * df["Trend_Score_100"]
        + df["Fair_Value_Weight"] * df["Tuned_Fair_Value_Score"]
    )
    return df


def mode_or_neutral(values: pd.Series) -> str:
    clean = values.dropna().astype(str)
    if clean.empty:
        return "Neutral"
    mode = clean.mode()
    return str(mode.iloc[0]) if not mode.empty else "Neutral"


def score_anchor_horizons(
    config: WeightConfig,
    day: pd.DataFrame,
    price_wide: pd.DataFrame,
    top_n: int,
    include_risk_metrics: bool,
    save_holdings: bool,
) -> tuple[list[dict], list[dict]]:
    anchor = pd.to_datetime(day["Date"].iloc[0]).normalize()
    ranked = day.sort_values("Tuned_Combined_Score", ascending=False).copy()
    top = ranked.head(top_n).copy()
    end_date = price_wide.index.max()

    results = []
    holdings = []

    for horizon_name, horizon_days in HORIZONS.items():
        future_date, returns = regime_bt.future_return_series(price_wide, anchor, horizon_days)
        if future_date is None or returns.empty:
            continue

        top_returns = returns.reindex(top["Ticker"]).dropna()
        universe_returns = returns.reindex(ranked["Ticker"]).dropna()
        if top_returns.empty or universe_returns.empty:
            continue

        qqq_return = regime_bt.benchmark_value(returns, "QQQ")
        xlk_return = regime_bt.benchmark_value(returns, "XLK")
        top_avg = float(top_returns.mean())
        universe_avg = float(universe_returns.mean())

        risk_metrics = {}
        if include_risk_metrics:
            risk_metrics = portfolio_metrics.portfolio_risk_metrics(
                price_wide=price_wide,
                top_tickers=top["Ticker"],
                universe_tickers=ranked["Ticker"],
                anchor=anchor,
                future_date=future_date,
                benchmark_ticker="XLK",
            )

        results.append({
            "Config_ID": config.config_id,
            "Fold": regime_bt.fold_label(anchor, end_date),
            "Anchor_Date": anchor.strftime("%Y-%m-%d"),
            "Future_Date": future_date.strftime("%Y-%m-%d"),
            "Horizon": horizon_name,
            "Top_N": top_n,
            "Ranked_Count": int(len(ranked)),
            "Top_Count_With_Return": int(top_returns.count()),
            "Ranked_Count_With_Return": int(universe_returns.count()),
            "Top_Avg_Return": top_avg,
            "Top_Median_Return": float(top_returns.median()),
            "Universe_Avg_Return": universe_avg,
            "Universe_Median_Return": float(universe_returns.median()),
            "QQQ_Return": qqq_return,
            "XLK_Return": xlk_return,
            "Top_Excess_vs_Universe": top_avg - universe_avg,
            "Top_Excess_vs_QQQ": top_avg - qqq_return if np.isfinite(qqq_return) else np.nan,
            "Top_Excess_vs_XLK": top_avg - xlk_return if np.isfinite(xlk_return) else np.nan,
            "Hit_Rate_vs_Universe_Avg": float((top_returns > universe_avg).mean()),
            "Top_Avg_Tuned_Combined_Score": portfolio_metrics.finite_mean(top["Tuned_Combined_Score"]),
            "Top_Avg_Fair_Value_Score": portfolio_metrics.finite_mean(top["Tuned_Fair_Value_Score"]),
            "Top_Avg_Price_Trend_Score": portfolio_metrics.finite_mean(top["Trend_Score_100"]),
            "Top_Avg_Trend_Weight": portfolio_metrics.finite_mean(top["Trend_Weight"]),
            "Industry_Regime": mode_or_neutral(day["Industry_Regime"]),
            "Bullish_Subindustry_Count": int(day["SubIndustry_Regime"].isin(["Bull", "EarlyBull"]).groupby(day["SubIndustry"]).max().sum()),
            "Bear_Subindustry_Count": int((day["SubIndustry_Regime"] == "Bear").groupby(day["SubIndustry"]).max().sum()),
            "Neutral_Subindustry_Count": int((day["SubIndustry_Regime"] == "Neutral").groupby(day["SubIndustry"]).max().sum()),
            **risk_metrics,
            **portfolio_metrics.cross_sectional_return_metrics("Top", top_returns),
        })

        if save_holdings:
            holding_frame = top.copy()
            holding_frame["Config_ID"] = config.config_id
            holding_frame["Anchor_Date"] = anchor.strftime("%Y-%m-%d")
            holding_frame["Horizon"] = horizon_name
            holding_frame["Forward_Return"] = holding_frame["Ticker"].map(returns)
            holding_frame["Tuned_Rank"] = np.arange(1, len(holding_frame) + 1)
            holding_cols = [
                "Config_ID",
                "Anchor_Date",
                "Horizon",
                "Tuned_Rank",
                "Ticker",
                "SubIndustry",
                "Tuned_Combined_Score",
                "Tuned_Fair_Value_Score",
                "Trend_Score_100",
                "Trend_Weight",
                "Fair_Value_Weight",
                "Industry_Regime",
                "SubIndustry_Regime",
                "Forward_Return",
            ]
            holdings.extend(holding_frame[[col for col in holding_cols if col in holding_frame.columns]].to_dict("records"))

    return results, holdings


def evaluate_config(
    scores: pd.DataFrame,
    config: WeightConfig,
    price_wide: pd.DataFrame,
    top_n: int,
    include_risk_metrics: bool,
    save_holdings: bool,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    scored = config_score_frame(scores, config)
    if scored.empty:
        return pd.DataFrame(), pd.DataFrame()

    result_rows = []
    holding_rows = []
    for _, day in scored.groupby("Date", sort=True):
        results, holdings = score_anchor_horizons(
            config=config,
            day=day,
            price_wide=price_wide,
            top_n=top_n,
            include_risk_metrics=include_risk_metrics,
            save_holdings=save_holdings,
        )
        result_rows.extend(results)
        holding_rows.extend(holdings)

    return pd.DataFrame(result_rows), pd.DataFrame(holding_rows)


def aggregate_results(results: pd.DataFrame, group_cols: list[str]) -> pd.DataFrame:
    if results.empty:
        return pd.DataFrame()

    aggregations = {
        "Observations": ("Top_Avg_Return", "count"),
        "Top_Avg_Return": ("Top_Avg_Return", "mean"),
        "Universe_Avg_Return": ("Universe_Avg_Return", "mean"),
        "QQQ_Return": ("QQQ_Return", "mean"),
        "XLK_Return": ("XLK_Return", "mean"),
        "Top_Excess_vs_Universe": ("Top_Excess_vs_Universe", "mean"),
        "Top_Excess_vs_QQQ": ("Top_Excess_vs_QQQ", "mean"),
        "Top_Excess_vs_XLK": ("Top_Excess_vs_XLK", "mean"),
        "Hit_Rate_vs_Universe_Avg": ("Hit_Rate_vs_Universe_Avg", "mean"),
        "Avg_Ranked_Count": ("Ranked_Count", "mean"),
        "Avg_Top_Trend_Weight": ("Top_Avg_Trend_Weight", "mean"),
        "Avg_Top_Annualized_Volatility": ("Top_Annualized_Volatility", "mean"),
        "Avg_Top_Sharpe": ("Top_Sharpe", "mean"),
        "Avg_Top_Sortino": ("Top_Sortino", "mean"),
        "Avg_Top_Max_Drawdown": ("Top_Max_Drawdown", "mean"),
        "Avg_Top_Return_To_Drawdown": ("Top_Return_To_Drawdown", "mean"),
        "Avg_Top_Downside_Capture_vs_XLK": ("Top_Downside_Capture_vs_XLK", "mean"),
        "Avg_Top_Upside_Capture_vs_XLK": ("Top_Upside_Capture_vs_XLK", "mean"),
        "Avg_Top_Tracking_Error_vs_XLK": ("Top_Tracking_Error_vs_XLK", "mean"),
        "Avg_Top_Information_Ratio_vs_XLK": ("Top_Information_Ratio_vs_XLK", "mean"),
        "Avg_Top_Loss_Rate": ("Top_Loss_Rate", "mean"),
        "Avg_Top_CrossSection_Return_Std": ("Top_CrossSection_Return_Std", "mean"),
    }
    aggregations = {
        out_col: (in_col, agg_func)
        for out_col, (in_col, agg_func) in aggregations.items()
        if in_col in results.columns
    }
    return (
        results
        .groupby(group_cols, dropna=False)
        .agg(**aggregations)
        .reset_index()
        .round(6)
    )


def score_configs(results: pd.DataFrame) -> pd.DataFrame:
    scorecard = aggregate_results(results, ["Config_ID"])
    if scorecard.empty:
        return scorecard

    downside_capture = scorecard.get("Avg_Top_Downside_Capture_vs_XLK", pd.Series(np.nan, index=scorecard.index))
    downside_penalty = (downside_capture - 1.0).clip(lower=0.0).fillna(0.0)
    drawdown_penalty = scorecard.get("Avg_Top_Max_Drawdown", pd.Series(np.nan, index=scorecard.index)).abs().fillna(0.0)

    scorecard["Return_Objective"] = (
        scorecard["Top_Excess_vs_Universe"].fillna(0.0)
        + 0.50 * scorecard["Top_Excess_vs_XLK"].fillna(0.0)
    )
    scorecard["Risk_Adjusted_Objective"] = (
        scorecard["Return_Objective"]
        + 0.010 * scorecard.get("Avg_Top_Sharpe", pd.Series(0.0, index=scorecard.index)).fillna(0.0)
        + 0.005 * scorecard.get("Avg_Top_Information_Ratio_vs_XLK", pd.Series(0.0, index=scorecard.index)).fillna(0.0)
        - 0.050 * downside_penalty
        - 0.020 * drawdown_penalty
    )
    return scorecard.sort_values("Risk_Adjusted_Objective", ascending=False).reset_index(drop=True)


def walk_forward_selection(results: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    selection_rows = []
    validation_frames = []
    available_folds = [fold for fold in FOLD_ORDER if fold in set(results["Fold"])]

    for validation_idx in range(1, len(available_folds)):
        validation_fold = available_folds[validation_idx]
        train_folds = available_folds[:validation_idx]
        train_results = results[results["Fold"].isin(train_folds)].copy()
        validation_results = results[results["Fold"] == validation_fold].copy()
        if train_results.empty or validation_results.empty:
            continue

        train_scorecard = score_configs(train_results)
        if train_scorecard.empty:
            continue

        selected_id = str(train_scorecard.iloc[0]["Config_ID"])
        selected_validation = validation_results[validation_results["Config_ID"] == selected_id].copy()
        validation_scorecard = score_configs(selected_validation)
        validation_summary = validation_scorecard.iloc[0].to_dict() if not validation_scorecard.empty else {}

        selected_validation["Walk_Forward_Round"] = len(selection_rows) + 1
        selected_validation["Train_Folds"] = ",".join(train_folds)
        validation_frames.append(selected_validation)

        selection_rows.append({
            "Walk_Forward_Round": len(selection_rows) + 1,
            "Train_Folds": ",".join(train_folds),
            "Validation_Fold": validation_fold,
            "Selected_Config_ID": selected_id,
            "Train_Risk_Adjusted_Objective": float(train_scorecard.iloc[0]["Risk_Adjusted_Objective"]),
            "Train_Return_Objective": float(train_scorecard.iloc[0]["Return_Objective"]),
            "Validation_Risk_Adjusted_Objective": validation_summary.get("Risk_Adjusted_Objective", np.nan),
            "Validation_Return_Objective": validation_summary.get("Return_Objective", np.nan),
            "Validation_Top_Excess_vs_Universe": validation_summary.get("Top_Excess_vs_Universe", np.nan),
            "Validation_Top_Excess_vs_XLK": validation_summary.get("Top_Excess_vs_XLK", np.nan),
            "Validation_Avg_Top_Sharpe": validation_summary.get("Avg_Top_Sharpe", np.nan),
            "Validation_Avg_Top_Max_Drawdown": validation_summary.get("Avg_Top_Max_Drawdown", np.nan),
            "Validation_Avg_Top_Downside_Capture_vs_XLK": validation_summary.get("Avg_Top_Downside_Capture_vs_XLK", np.nan),
        })

    validation = (
        pd.concat(validation_frames, ignore_index=True, sort=False)
        if validation_frames else pd.DataFrame()
    )
    return pd.DataFrame(selection_rows).round(6), validation


def write_summary(
    output_dir: Path,
    scorecard: pd.DataFrame,
    horizon_summary: pd.DataFrame,
    walk_forward: pd.DataFrame,
    walk_forward_overall: pd.DataFrame,
    configs: list[WeightConfig],
    metadata: dict,
) -> None:
    top = scorecard.iloc[0].to_dict() if not scorecard.empty else {}
    current = (
        scorecard[scorecard["Config_ID"] == "current_live"].iloc[0].to_dict()
        if not scorecard.empty and "current_live" in set(scorecard["Config_ID"])
        else {}
    )
    selections = (
        walk_forward["Selected_Config_ID"].value_counts().to_dict()
        if not walk_forward.empty else {}
    )

    lines = [
        "# Walk-Forward Weight Tuning Summary",
        "",
        "## What was completed",
        "",
        "This run tuned the combined-score weight matrix using the existing point-in-time fair-value history.",
        "It did not re-scrape SEC data; it reused the historical score snapshots where each fair-value score was already filtered by SEC filing date.",
        "",
        "The tested score formula was:",
        "",
        "`combined = trend_weight_by_regime * price_trend_score + (1 - trend_weight_by_regime) * fair_value_score`",
        "",
        "Risk-adjusted metrics were added for each candidate/horizon, including volatility, Sharpe, Sortino, max drawdown, return-to-drawdown, tracking error vs XLK, information ratio vs XLK, upside capture, downside capture, holding loss rate, and cross-sectional return dispersion.",
        "",
        "## Run configuration",
        "",
        f"- Candidate configs tested: {metadata.get('candidate_config_count')}",
        f"- Top-N portfolio size: {metadata.get('top_n')}",
        f"- Score rows loaded: {metadata.get('score_rows')}",
        f"- Anchor dates loaded: {metadata.get('anchor_count')}",
        f"- Price start: {metadata.get('price_start_date')}",
        f"- Price end: {metadata.get('price_end_date')}",
        f"- Latest price date: {metadata.get('latest_price_date')}",
        "",
        "## Best full-sample candidate",
        "",
    ]

    if top:
        lines.extend([
            f"- Config: `{top.get('Config_ID')}`",
            f"- Risk-adjusted objective: {top.get('Risk_Adjusted_Objective')}",
            f"- Return objective: {top.get('Return_Objective')}",
            f"- Excess vs universe: {top.get('Top_Excess_vs_Universe')}",
            f"- Excess vs XLK: {top.get('Top_Excess_vs_XLK')}",
            f"- Avg Sharpe: {top.get('Avg_Top_Sharpe')}",
            f"- Avg max drawdown: {top.get('Avg_Top_Max_Drawdown')}",
            "",
        ])
    else:
        lines.extend(["No candidate scorecard was produced.", ""])

    lines.extend([
        "## Current live config comparison",
        "",
    ])
    if current:
        lines.extend([
            f"- Risk-adjusted objective: {current.get('Risk_Adjusted_Objective')}",
            f"- Return objective: {current.get('Return_Objective')}",
            f"- Excess vs universe: {current.get('Top_Excess_vs_Universe')}",
            f"- Excess vs XLK: {current.get('Top_Excess_vs_XLK')}",
            f"- Avg Sharpe: {current.get('Avg_Top_Sharpe')}",
            f"- Avg max drawdown: {current.get('Avg_Top_Max_Drawdown')}",
            "",
        ])
    else:
        lines.extend(["The current live config was not found in the scorecard.", ""])

    lines.extend([
        "## Walk-forward validation",
        "",
    ])
    if selections:
        lines.append("Selected config counts:")
        for config_id, count in selections.items():
            lines.append(f"- `{config_id}`: {count}")
        lines.append("")

    if not walk_forward_overall.empty:
        wf = walk_forward_overall.iloc[0].to_dict()
        lines.extend([
            "Aggregate validation result of the configs selected only from older folds:",
            f"- Observations: {wf.get('Observations')}",
            f"- Avg top return: {wf.get('Top_Avg_Return')}",
            f"- Avg universe return: {wf.get('Universe_Avg_Return')}",
            f"- Avg XLK return: {wf.get('XLK_Return')}",
            f"- Excess vs universe: {wf.get('Top_Excess_vs_Universe')}",
            f"- Excess vs XLK: {wf.get('Top_Excess_vs_XLK')}",
            f"- Avg Sharpe: {wf.get('Avg_Top_Sharpe')}",
            f"- Avg max drawdown: {wf.get('Avg_Top_Max_Drawdown')}",
            f"- Avg downside capture vs XLK: {wf.get('Avg_Top_Downside_Capture_vs_XLK')}",
            "",
        ])
    else:
        lines.extend(["Walk-forward validation did not produce enough fold data.", ""])

    lines.extend([
        "## Interpretation",
        "",
        "This tuning layer is now wired and usable. Treat the best full-sample candidate as a research lead, not an automatic production change. The walk-forward validation rows are the more important evidence because each validation fold is scored by weights selected from earlier data only.",
        "",
        "Production decision: do not patch `comp.py` with the full-sample winner yet unless the walk-forward validation improves. In this run, the validation layer is intentionally the gatekeeper because it tests whether a weight choice selected from older data survives the next unseen fold.",
        "",
        "## Files produced",
        "",
        "- `candidate_configs.csv`",
        "- `candidate_results.csv`",
        "- `candidate_summary_by_horizon.csv`",
        "- `candidate_scorecard.csv`",
        "- `walk_forward_selected_configs.csv`",
        "- `walk_forward_validation_results.csv`",
        "- `walk_forward_summary.csv`",
        "- `walk_forward_round_summary.csv`",
        "- `walk_forward_validation_scorecard.csv`",
        "- `recommended_weights.json`",
        "- `candidate_top_holdings.csv` when `--save-holdings` is used",
        "- `WEIGHT_TUNING_SUMMARY.md`",
    ])

    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "WEIGHT_TUNING_SUMMARY.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Walk-forward tune combined-score weight matrices.")
    parser.add_argument("--score-history", type=Path, default=DEFAULT_SCORE_HISTORY)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument(
        "--historical-price-file",
        type=Path,
        help=(
            "Optional canonical daily price CSV from historical_data_layer.py. "
            "Use this for Sharadar active/delisted prices instead of Yahoo."
        ),
    )
    parser.add_argument("--preset", choices=["compact", "expanded"], default="expanded")
    parser.add_argument("--top-n", type=int, default=100)
    parser.add_argument("--batch-size", type=int, default=25)
    parser.add_argument("--skip-risk-metrics", action="store_true")
    parser.add_argument("--save-holdings", action="store_true")
    parser.add_argument("--max-configs", type=int)
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    scores = prepare_score_history(args.score_history)
    configs = build_candidate_configs(args.preset)
    if args.max_configs is not None:
        configs = configs[:args.max_configs]
    if not configs:
        raise RuntimeError("No candidate configs selected")

    print(f"[INFO] Loaded {len(scores):,} point-in-time score rows", flush=True)
    print(f"[INFO] Testing {len(configs)} weight configs", flush=True)
    price_wide = fetch_price_wide(
        scores,
        args.batch_size,
        historical_price_file=args.historical_price_file,
    )
    print(f"[INFO] Price matrix: {len(price_wide):,} dates x {len(price_wide.columns):,} tickers", flush=True)

    all_results = []
    all_holdings = []
    for idx, config in enumerate(configs, start=1):
        print(f"[INFO] Evaluating config {idx}/{len(configs)}: {config.config_id}", flush=True)
        config_results, config_holdings = evaluate_config(
            scores=scores,
            config=config,
            price_wide=price_wide,
            top_n=args.top_n,
            include_risk_metrics=not args.skip_risk_metrics,
            save_holdings=args.save_holdings,
        )
        all_results.append(config_results)
        if args.save_holdings:
            all_holdings.append(config_holdings)

    results = pd.concat(all_results, ignore_index=True, sort=False) if all_results else pd.DataFrame()
    holdings = pd.concat(all_holdings, ignore_index=True, sort=False) if all_holdings else pd.DataFrame()
    horizon_summary = aggregate_results(results, ["Config_ID", "Horizon"])
    scorecard = score_configs(results)
    walk_forward, validation_results = walk_forward_selection(results)
    walk_forward_round_summary = aggregate_results(validation_results, ["Walk_Forward_Round"]) if not validation_results.empty else pd.DataFrame()
    walk_forward_overall = (
        score_configs(validation_results.assign(Config_ID="walk_forward_selected"))
        if not validation_results.empty else pd.DataFrame()
    )
    validation_scorecard = score_configs(validation_results) if not validation_results.empty else pd.DataFrame()

    metadata = {
        "status": "complete",
        "score_history": str(args.score_history),
        "historical_price_file": str(args.historical_price_file) if args.historical_price_file else None,
        "market_data_source": str(args.historical_price_file) if args.historical_price_file else "yfinance",
        "preset": args.preset,
        "top_n": args.top_n,
        "score_rows": int(len(scores)),
        "anchor_count": int(scores["Date"].nunique()),
        "candidate_config_count": int(len(configs)),
        "price_start_date": scores["Date"].min().strftime("%Y-%m-%d"),
        "price_end_date": price_wide.index.max().strftime("%Y-%m-%d"),
        "latest_price_date": price_wide.index.max().strftime("%Y-%m-%d"),
        "risk_metrics_included": not args.skip_risk_metrics,
        "top_holdings_saved": args.save_holdings,
        "objective_note": (
            "Risk_Adjusted_Objective = excess vs universe + 0.5 * excess vs XLK "
            "+ 0.010 * Sharpe + 0.005 * information ratio - downside/drawdown penalties."
        ),
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([asdict(config) for config in configs]).to_csv(args.output_dir / "candidate_configs.csv", index=False)
    results.to_csv(args.output_dir / "candidate_results.csv", index=False)
    if args.save_holdings:
        holdings.to_csv(args.output_dir / "candidate_top_holdings.csv", index=False)
    horizon_summary.to_csv(args.output_dir / "candidate_summary_by_horizon.csv", index=False)
    scorecard.to_csv(args.output_dir / "candidate_scorecard.csv", index=False)
    walk_forward.to_csv(args.output_dir / "walk_forward_selected_configs.csv", index=False)
    validation_results.to_csv(args.output_dir / "walk_forward_validation_results.csv", index=False)
    walk_forward_round_summary.to_csv(args.output_dir / "walk_forward_round_summary.csv", index=False)
    walk_forward_overall.to_csv(args.output_dir / "walk_forward_summary.csv", index=False)
    validation_scorecard.to_csv(args.output_dir / "walk_forward_validation_scorecard.csv", index=False)
    (args.output_dir / "run_metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    recommended = {
        "best_full_sample": scorecard.iloc[0].to_dict() if not scorecard.empty else {},
        "current_live": (
            scorecard[scorecard["Config_ID"] == "current_live"].iloc[0].to_dict()
            if not scorecard.empty and "current_live" in set(scorecard["Config_ID"])
            else {}
        ),
        "walk_forward_selected_config_counts": (
            walk_forward["Selected_Config_ID"].value_counts().to_dict()
            if not walk_forward.empty else {}
        ),
        "candidate_parameters": {
            config.config_id: asdict(config)
            for config in configs
        },
        "recommendation_note": (
            "Do not automatically patch production weights from the full-sample winner. "
            "Use walk-forward validation stability before changing comp.py."
        ),
    }
    (args.output_dir / "recommended_weights.json").write_text(
        json.dumps(recommended, indent=2, default=str),
        encoding="utf-8",
    )
    write_summary(
        output_dir=args.output_dir,
        scorecard=scorecard,
        horizon_summary=horizon_summary,
        walk_forward=walk_forward,
        walk_forward_overall=walk_forward_overall,
        configs=configs,
        metadata=metadata,
    )

    print("\n=== WEIGHT TUNING SCORECARD ===", flush=True)
    cols = [
        "Config_ID",
        "Risk_Adjusted_Objective",
        "Return_Objective",
        "Top_Excess_vs_Universe",
        "Top_Excess_vs_XLK",
        "Avg_Top_Sharpe",
        "Avg_Top_Max_Drawdown",
        "Avg_Top_Downside_Capture_vs_XLK",
    ]
    if not scorecard.empty:
        print(scorecard[[col for col in cols if col in scorecard.columns]].head(10).to_string(index=False), flush=True)

    print("\n=== WALK-FORWARD SELECTIONS ===", flush=True)
    if walk_forward.empty:
        print("[WARN] No walk-forward selections were produced.", flush=True)
    else:
        print(walk_forward.to_string(index=False), flush=True)

    print(f"\n[SUCCESS] Saved walk-forward tuning outputs to {args.output_dir}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
