#!/usr/bin/env python3
"""Forward paper-test tracker for the current Stock Analysis research default.

This script never places trades and never connects to a broker. It initializes
or updates a simple paper ledger from the website-facing production-default
holdings generated by ``generate_website_assets.py``.
"""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd


DEFAULT_HOLDINGS_FILE = Path("website_assets/production-default-latest-holdings.csv")
DEFAULT_PRICE_FILE = Path("data/historical_data_layer/prices_daily.csv")
DEFAULT_OUTPUT_DIR = Path("paper_tests")
DEFAULT_INITIAL_CAPITAL = 100_000.0
DEFAULT_CONFIG_ID = "alpha_Alpha_Prototype_XLKCompetitive"
DEFAULT_TOP_N = 10
DEFAULT_PORTFOLIO_MODE = "rank_weighted"

POSITIONS_FILE = "production_default_paper_positions.csv"
EQUITY_FILE = "production_default_paper_equity.csv"
SUMMARY_FILE = "PAPER_TEST_SUMMARY.md"
METADATA_FILE = "production_default_paper_metadata.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Update the Stock Analysis forward paper test.")
    parser.add_argument("--holdings-file", type=Path, default=DEFAULT_HOLDINGS_FILE)
    parser.add_argument("--price-file", type=Path, default=DEFAULT_PRICE_FILE)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--initial-capital", type=float, default=DEFAULT_INITIAL_CAPITAL)
    parser.add_argument("--config-id", default=DEFAULT_CONFIG_ID)
    parser.add_argument("--top-n", type=int, default=DEFAULT_TOP_N)
    parser.add_argument("--portfolio-mode", default=DEFAULT_PORTFOLIO_MODE)
    parser.add_argument("--reset", action="store_true", help="Re-initialize the paper test from current holdings.")
    return parser.parse_args()


def utc_timestamp() -> str:
    return datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")


def read_csv_if_exists(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def normalize_ticker_list(tickers: set[str] | list[str] | pd.Series) -> set[str]:
    return {str(t).upper().strip() for t in tickers if str(t).strip()}


def load_latest_prices(
    price_file: Path,
    tickers: set[str],
    on_or_before: pd.Timestamp | None = None,
) -> pd.DataFrame:
    if not price_file.exists():
        raise FileNotFoundError(f"Canonical price file not found: {price_file}")

    tickers = normalize_ticker_list(tickers)
    if not tickers:
        return pd.DataFrame(columns=["Ticker", "Date", "Close"])

    chunks: list[pd.DataFrame] = []
    usecols = ["Ticker", "Date", "Close"]
    for chunk in pd.read_csv(price_file, usecols=usecols, chunksize=500_000):
        chunk["Ticker"] = chunk["Ticker"].astype(str).str.upper().str.strip()
        chunk = chunk[chunk["Ticker"].isin(tickers)].copy()
        if chunk.empty:
            continue
        chunk["Date"] = pd.to_datetime(chunk["Date"], errors="coerce").dt.normalize()
        chunk["Close"] = pd.to_numeric(chunk["Close"], errors="coerce")
        chunk = chunk.dropna(subset=["Ticker", "Date", "Close"])
        if on_or_before is not None:
            cutoff = pd.to_datetime(on_or_before).normalize()
            chunk = chunk[chunk["Date"] <= cutoff]
        if not chunk.empty:
            chunks.append(chunk)

    if not chunks:
        return pd.DataFrame(columns=["Ticker", "Date", "Close"])

    prices = pd.concat(chunks, ignore_index=True)
    prices = prices.sort_values(["Ticker", "Date"]).drop_duplicates(["Ticker", "Date"], keep="last")
    return prices.groupby("Ticker", as_index=False).tail(1).reset_index(drop=True)


def latest_price_maps(price_file: Path, tickers: set[str], on_or_before: pd.Timestamp | None = None) -> tuple[dict[str, float], dict[str, str]]:
    latest = load_latest_prices(price_file, tickers, on_or_before=on_or_before)
    price_map = latest.set_index("Ticker")["Close"].to_dict()
    date_map = latest.set_index("Ticker")["Date"].dt.strftime("%Y-%m-%d").to_dict()
    return price_map, date_map


def count_observed_trading_days(
    price_file: Path,
    benchmark: str,
    start_date: pd.Timestamp,
    end_date: pd.Timestamp,
) -> int:
    if pd.isna(start_date) or pd.isna(end_date) or end_date <= start_date:
        return 0

    benchmark = str(benchmark).upper().strip()
    dates: set[pd.Timestamp] = set()
    usecols = ["Ticker", "Date"]
    for chunk in pd.read_csv(price_file, usecols=usecols, chunksize=500_000):
        chunk["Ticker"] = chunk["Ticker"].astype(str).str.upper().str.strip()
        chunk = chunk[chunk["Ticker"] == benchmark].copy()
        if chunk.empty:
            continue
        chunk["Date"] = pd.to_datetime(chunk["Date"], errors="coerce").dt.normalize()
        chunk = chunk[(chunk["Date"] > start_date) & (chunk["Date"] <= end_date)]
        dates.update(chunk["Date"].dropna().tolist())
    return len(dates)


def select_holdings(
    holdings_file: Path,
    config_id: str,
    top_n: int,
    portfolio_mode: str,
) -> pd.DataFrame:
    if not holdings_file.exists():
        raise FileNotFoundError(f"Latest holdings file not found: {holdings_file}")

    holdings = pd.read_csv(holdings_file)
    required = {"Config_ID", "Top_N", "Portfolio_Mode", "Ticker", "Target_Weight", "Trade_Date"}
    missing = sorted(required - set(holdings.columns))
    if missing:
        raise RuntimeError(f"Holdings file missing required columns: {missing}")

    selected = holdings[
        (holdings["Config_ID"].astype(str) == config_id)
        & (pd.to_numeric(holdings["Top_N"], errors="coerce") == top_n)
        & (holdings["Portfolio_Mode"].astype(str) == portfolio_mode)
    ].copy()
    if selected.empty:
        raise RuntimeError("No holdings matched the requested production-default configuration")

    selected["Ticker"] = selected["Ticker"].astype(str).str.upper().str.strip()
    selected["Target_Weight"] = pd.to_numeric(selected["Target_Weight"], errors="coerce").fillna(0.0)
    selected = selected[selected["Target_Weight"] > 0].copy()
    if selected.empty:
        raise RuntimeError("Matched holdings have no positive target weights")

    selected["Trade_Date"] = pd.to_datetime(selected["Trade_Date"], errors="coerce").dt.normalize()
    selected = selected.dropna(subset=["Trade_Date"])
    if selected.empty:
        raise RuntimeError("Matched holdings have no valid trade date")

    return selected.sort_values("Portfolio_Rank").reset_index(drop=True)


def initialize_positions(args: argparse.Namespace) -> tuple[pd.DataFrame, dict]:
    holdings = select_holdings(
        holdings_file=args.holdings_file,
        config_id=args.config_id,
        top_n=args.top_n,
        portfolio_mode=args.portfolio_mode,
    )
    entry_date = pd.to_datetime(holdings["Trade_Date"].max()).normalize()
    tickers = normalize_ticker_list(holdings["Ticker"]) | {"QQQ", "XLK"}
    entry_prices, entry_price_dates = latest_price_maps(args.price_file, tickers, on_or_before=entry_date)

    rows = []
    invested_value = 0.0
    missing_prices = []
    for _, row in holdings.iterrows():
        ticker = row["Ticker"]
        entry_price = entry_prices.get(ticker)
        if entry_price is None or not np.isfinite(float(entry_price)) or float(entry_price) <= 0:
            missing_prices.append(ticker)
            continue

        target_weight = float(row["Target_Weight"])
        entry_value = float(args.initial_capital) * target_weight
        shares = entry_value / float(entry_price)
        invested_value += entry_value
        rows.append({
            "Paper_Test_ID": f"{args.config_id}_{entry_date.strftime('%Y%m%d')}",
            "Initialized_At": utc_timestamp(),
            "Entry_Date": entry_date.strftime("%Y-%m-%d"),
            "Ticker": ticker,
            "SubIndustry": row.get("SubIndustry", ""),
            "Portfolio_Rank": row.get("Portfolio_Rank", np.nan),
            "Target_Weight": target_weight,
            "Entry_Price": float(entry_price),
            "Entry_Price_Date": entry_price_dates.get(ticker, ""),
            "Shares": shares,
            "Entry_Value": entry_value,
            "Signal_Score": row.get("Tuned_Combined_Score", np.nan),
            "Fair_Value_Score": row.get("Tuned_Fair_Value_Score", np.nan),
            "Trend_Score_100": row.get("Trend_Score_100", np.nan),
            "ADV20_Dollar": row.get("ADV20_Dollar", np.nan),
            "Config_ID": args.config_id,
            "Top_N": args.top_n,
            "Portfolio_Mode": args.portfolio_mode,
        })

    if not rows:
        raise RuntimeError(f"No paper positions could be initialized. Missing prices: {missing_prices}")

    positions = pd.DataFrame(rows)
    cash = max(float(args.initial_capital) - invested_value, 0.0)
    benchmark_entries = {
        ticker: {
            "entry_price": entry_prices.get(ticker),
            "entry_price_date": entry_price_dates.get(ticker, ""),
        }
        for ticker in ["QQQ", "XLK"]
    }
    metadata = {
        "paper_test_id": positions["Paper_Test_ID"].iloc[0],
        "status": "active",
        "research_only": True,
        "no_real_trades": True,
        "initialized_at": utc_timestamp(),
        "entry_date": entry_date.strftime("%Y-%m-%d"),
        "initial_capital": float(args.initial_capital),
        "cash_usd": cash,
        "invested_value": invested_value,
        "invested_weight": invested_value / float(args.initial_capital),
        "config_id": args.config_id,
        "top_n": args.top_n,
        "portfolio_mode": args.portfolio_mode,
        "holdings_file": str(args.holdings_file),
        "price_file": str(args.price_file),
        "benchmark_entries": benchmark_entries,
        "missing_position_entry_prices": missing_prices,
    }
    return positions, metadata


def load_or_initialize(args: argparse.Namespace) -> tuple[pd.DataFrame, dict, bool]:
    args.output_dir.mkdir(parents=True, exist_ok=True)
    positions_path = args.output_dir / POSITIONS_FILE
    metadata_path = args.output_dir / METADATA_FILE

    if args.reset or not positions_path.exists() or not metadata_path.exists():
        positions, metadata = initialize_positions(args)
        positions.to_csv(positions_path, index=False)
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        return positions, metadata, True

    positions = pd.read_csv(positions_path)
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    return positions, metadata, False


def update_equity(args: argparse.Namespace, positions: pd.DataFrame, metadata: dict) -> pd.DataFrame:
    tickers = normalize_ticker_list(positions["Ticker"]) | {"QQQ", "XLK"}
    latest_prices, latest_price_dates = latest_price_maps(args.price_file, tickers)
    if not latest_prices:
        raise RuntimeError("No current prices found for paper-test update")

    rows = []
    total_market_value = 0.0
    missing_current_prices = []
    for _, row in positions.iterrows():
        ticker = str(row["Ticker"]).upper().strip()
        current_price = latest_prices.get(ticker)
        if current_price is None or not np.isfinite(float(current_price)):
            missing_current_prices.append(ticker)
            current_price = np.nan
            market_value = np.nan
        else:
            market_value = float(row["Shares"]) * float(current_price)
            total_market_value += market_value

        rows.append({
            "Ticker": ticker,
            "Shares": float(row["Shares"]),
            "Entry_Price": float(row["Entry_Price"]),
            "Current_Price": current_price,
            "Current_Price_Date": latest_price_dates.get(ticker, ""),
            "Entry_Value": float(row["Entry_Value"]),
            "Market_Value": market_value,
            "Position_Return": (
                float(current_price) / float(row["Entry_Price"]) - 1.0
                if np.isfinite(float(current_price)) and float(row["Entry_Price"]) > 0
                else np.nan
            ),
            "Target_Weight": float(row["Target_Weight"]),
        })

    initial_capital = float(metadata["initial_capital"])
    cash = float(metadata.get("cash_usd", 0.0))
    equity = total_market_value + cash
    update_date = max(
        [pd.to_datetime(date, errors="coerce") for date in latest_price_dates.values() if date],
        default=pd.NaT,
    )
    update_date_str = "" if pd.isna(update_date) else update_date.strftime("%Y-%m-%d")

    benchmark_values = {}
    for benchmark in ["QQQ", "XLK"]:
        entry = metadata.get("benchmark_entries", {}).get(benchmark, {})
        entry_price = entry.get("entry_price")
        current_price = latest_prices.get(benchmark)
        if (
            entry_price is not None
            and current_price is not None
            and np.isfinite(float(entry_price))
            and np.isfinite(float(current_price))
            and float(entry_price) > 0
        ):
            benchmark_values[f"{benchmark}_Equity"] = initial_capital * float(current_price) / float(entry_price)
            benchmark_values[f"{benchmark}_Return"] = float(current_price) / float(entry_price) - 1.0
            benchmark_values[f"{benchmark}_Price_Date"] = latest_price_dates.get(benchmark, "")
        else:
            benchmark_values[f"{benchmark}_Equity"] = np.nan
            benchmark_values[f"{benchmark}_Return"] = np.nan
            benchmark_values[f"{benchmark}_Price_Date"] = ""

    entry_date = pd.to_datetime(metadata.get("entry_date"), errors="coerce").normalize()
    observed_trading_days = (
        count_observed_trading_days(args.price_file, "QQQ", entry_date, update_date)
        if not pd.isna(update_date) and not pd.isna(entry_date)
        else 0
    )
    total_return = equity / initial_capital - 1.0
    qqq_return = benchmark_values.get("QQQ_Return", np.nan)
    xlk_return = benchmark_values.get("XLK_Return", np.nan)

    equity_row = {
        "Date": update_date_str,
        "Updated_At": utc_timestamp(),
        "Paper_Test_ID": metadata.get("paper_test_id", ""),
        "Entry_Date": metadata.get("entry_date", ""),
        "Observed_Trading_Days": observed_trading_days,
        "Initial_Capital": initial_capital,
        "Equity": equity,
        "Invested_Market_Value": total_market_value,
        "Cash_USD": cash,
        "Total_Return": total_return,
        "Excess_Return_vs_QQQ": total_return - float(qqq_return) if np.isfinite(float(qqq_return)) else np.nan,
        "Excess_Return_vs_XLK": total_return - float(xlk_return) if np.isfinite(float(xlk_return)) else np.nan,
        "Missing_Current_Prices": ",".join(missing_current_prices),
        **benchmark_values,
    }

    equity_path = args.output_dir / EQUITY_FILE
    equity_history = read_csv_if_exists(equity_path)
    equity_history = pd.concat([equity_history, pd.DataFrame([equity_row])], ignore_index=True)
    equity_history = (
        equity_history
        .drop_duplicates(["Date", "Paper_Test_ID"], keep="last")
        .sort_values(["Date", "Paper_Test_ID"])
        .reset_index(drop=True)
    )
    equity_history.to_csv(equity_path, index=False)

    pd.DataFrame(rows).to_csv(args.output_dir / "production_default_paper_position_marks.csv", index=False)
    metadata["last_updated_at"] = utc_timestamp()
    metadata["last_price_date"] = update_date_str
    metadata["missing_current_prices"] = missing_current_prices
    (args.output_dir / METADATA_FILE).write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    return equity_history


def fmt_pct(value: object) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if not np.isfinite(number):
        return "n/a"
    return f"{number * 100:,.2f}%"


def fmt_money(value: object) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if not np.isfinite(number):
        return "n/a"
    return f"${number:,.2f}"


def write_summary(args: argparse.Namespace, positions: pd.DataFrame, metadata: dict, equity_history: pd.DataFrame, initialized: bool) -> None:
    latest = equity_history.tail(1).iloc[0]
    marks = read_csv_if_exists(args.output_dir / "production_default_paper_position_marks.csv")
    top_marks = marks.sort_values("Market_Value", ascending=False).head(10) if not marks.empty else pd.DataFrame()

    rows = []
    for _, row in top_marks.iterrows():
        rows.append(
            f"| {row['Ticker']} | {float(row['Target_Weight']) * 100:,.2f}% | "
            f"{fmt_money(row['Market_Value'])} | {fmt_pct(row['Position_Return'])} |"
        )
    table = "\n".join(rows) if rows else "| n/a | n/a | n/a | n/a |"

    text = f"""# Production Default Paper Test

Status: {"initialized and updated" if initialized else "updated"}

This is a forward paper test for the Stock Analysis research model. It is not financial advice, not a recommendation to buy or sell securities, and not connected to any broker or live order system.

Current paper-test snapshot:

- Paper test ID: `{metadata.get('paper_test_id', '')}`
- Entry date: `{metadata.get('entry_date', '')}`
- Latest price date: `{latest.get('Date', '')}`
- Observed unseen trading days: `{int(latest.get('Observed_Trading_Days', 0))}`
- Initial capital: `{fmt_money(latest.get('Initial_Capital'))}`
- Current equity: `{fmt_money(latest.get('Equity'))}`
- Paper return: `{fmt_pct(latest.get('Total_Return'))}`
- QQQ return over same paper window: `{fmt_pct(latest.get('QQQ_Return'))}`
- XLK return over same paper window: `{fmt_pct(latest.get('XLK_Return'))}`
- Excess return versus QQQ: `{fmt_pct(latest.get('Excess_Return_vs_QQQ'))}`
- Excess return versus XLK: `{fmt_pct(latest.get('Excess_Return_vs_XLK'))}`
- Cash held from simulator caps: `{fmt_money(latest.get('Cash_USD'))}`
- Position count: `{len(positions)}`

Current marked positions:

| Ticker | Target Weight | Market Value | Position Return |
| --- | ---: | ---: | ---: |
{table}

Use this only as a forward observation ledger. Do not trust the model as a real allocation assistant until it has accumulated enough unseen paper-test history and continues to pass benchmark-relative and drawdown-aware checks. The minimum review checkpoint is 60 unseen trading days; a stronger review should use 120+ unseen trading days.
"""
    (args.output_dir / SUMMARY_FILE).write_text(text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    positions, metadata, initialized = load_or_initialize(args)
    equity_history = update_equity(args, positions, metadata)
    write_summary(args, positions, metadata, equity_history, initialized)
    latest = equity_history.tail(1).iloc[0]
    print("[SUCCESS] Paper-test ledger updated")
    print(json.dumps({
        "output_dir": str(args.output_dir),
        "date": latest.get("Date", ""),
        "equity": float(latest.get("Equity", np.nan)),
        "total_return": float(latest.get("Total_Return", np.nan)),
        "initialized": initialized,
    }, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
